# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install Dependencies
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build
      run: wails build -nsis -platform windows/amd64

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apptest1023-amd64-installer
        path: build/bin/apptest1023-amd64-installer.exe  # Should match the name used in the build step

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: apptest1023-amd64-installer
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: apptest ${GITHUB_REF#refs/tags/}
          files: |
            apptest1023-amd64-installer.exe
       
permissions:
  contents: write
   
