# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
        
    - name: Install pnpm
    - uses: pnpm/action-setup@v2
      with:
          version: 8
          
    - name: Install Dependencies
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build
      run: wails build -nsis -platform windows/arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: apptest1023-amd64-installer
        path: build/bin/apptest1023-amd64-installer  # Should match the name used in the build step

