# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev nsis
        elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
        elif [[ "${{ matrix.os }}" == 'macOS-latest' ]]; then
        fi

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install Dependencies
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build for OS
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          wails build -nsis -platform linux/amd64
        elif [[ ${{ matrix.os }} == 'windows-latest' ]]; then
          wails build -nsis -platform windows/amd64
        elif [[ ${{ matrix.os }} == 'macOS-latest' ]]; then
          wails build -nsis -platform darwin/universal
        fi

    - name: Upload Artifact
      run: |
        mkdir -p ${{ runner.workspace }}/artifacts/${{ matrix.os }}
        cp -r build/bin/* ${{ runner.workspace }}/artifacts/${{ matrix.os }}        
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Download Artifacts
      run: |
          # Download build artifacts from all OSes
          mkdir -p artifacts
          cp -r ${{ runner.workspace }}/artifacts/* artifacts/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
